version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
      - maria_db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules
    ports:
      - 3000:3000

  mongo_db:
    image: "mongo:4.4"
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo

  maria_db:
      image: "mariadb:10.6"
      container_name: mariadb
      restart: always
      volumes:
        - maria_db:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MARIADB_ROOT_USER: root
        MARIADB_ROOT_PASSWORD: mariadb

volumes:
  mongo_db:
  maria_db:

