version: "3.7"
services:
  backend:
    container_name: backend
    network_mode: host
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - mariadb

  frontend:
    container_name: frontend
    network_mode: host
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITIAL_ROOT_USERNAME: root
      MONGO_INITIAL_ROOT_PASSWORD: mongo
      MONGO_INITIAL_DATABASE: db

  mariadb:
      image: "mariadb:10.6"
      container_name: mariadb
      restart: always
      volumes:
        - maria_db:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MARIADB_ROOT_USER: root
        MARIADB_ROOT_PASSWORD: mariadb

volumes:
  mongo_db:
  maria_db:

